### ISSUE TITLE
Continue watching if first command execution fails

### ISSUE THREAD

**Issue by jsiebern** [ulrikstrid/redemon#3]
Hey, I've been using `redemon` for a few days now and it works flawlessly.
I'm using it in esy with it's own command if you're curious:
`"watch": "esy x redemon -p ./src esy x Re_typescript",`

I noticed that the program exits if the first command execution throws an error but it does not if a subsequent execution throws. Is it possible to have it continue the process on a failed first execution?

**Comment by ulrikstrid** [comment]
I didn't see this when you posted it, but I can't repro this currently, I tried with `raise` but it seems to work.

**Comment by jsiebern** [comment]
Hm, yeah... It only breaks on some specific things, I'll try to specify it further. I'll close this for now until I have a repro (if ever).
